application: fcc-comments
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
    - name: jinja2
      version: "2.6"
    - name: numpy
      version: "1.6.1"

includes:
    - mapreduce/include.yaml

handlers:
    - url: "/static"
      static_dir: static
      expiration: 30d

    - url: "/favicon.ico"
      static_files: "static/favicon.ico"
      upload: "static/favicon.ico"
      expiration: 1d

    - url: "/comment/(.*)/(.*)"
      script: main.app

    - url: "/"
      script: main.app

