application: fcc-comments
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

includes:
    - mapreduce/include.yaml

handlers:
- url: "/static"
  static_dir: static

- url: "/"
  script: main.app

